### ISSUE TITLE
Exec format error while connect to remote machine

### ISSUE THREAD

**Issue by NoirJ0e** [xxh/xxh-shell-zsh#8]
**Local OS (where xxh is installed):**
Local OS: macOS 10.15.7
**Destination host OS:**
Destination host OS: Ubuntu 18.04.5 LTS aarch64
**xxh version:**
xxh version: 0.8.7
**xxh-plugins installed:**
xxh-plugins installed: xxh-zsh
**Steps to Reproduce**
1. I run `xxh noir@192.168.0.200 +s zsh`
2. The output log: 
```
noir@192.168.0.200's password:
192.168.0.200:/home/noir/.xxh/.xxh/shells/xxh-shell-zsh not found. Install xxh-shell-zsh? [Y/n] y
Install xxh-shell-zsh to 192.168.0.200:/home/noir/.xxh
First time upload using rsync (this will be omitted on the next connections)
First run xxh-shell-zsh on 192.168.0.200
Something went wrong while running zsh on host:
./zsh.sh: line 28: /home/noir/.xxh/.xxh/shells/xxh-shell-zsh/build/zsh-bin/bin/zsh: cannot execute binary file: Exec format error
/home/noir/.xxh/.xxh/shells/xxh-shell-zsh/build/zsh.sh: line 28: /home/noir/.xxh/.xxh/shells/xxh-shell-zsh/build/zsh-bin/bin/zsh: cannot execute binary file: Exec format error
```
3. What is the problem: I don't really know, maybe because the destination machine is an Arm64 device?

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
Hi @NoirJ0e ! 
You're trying to install [zsh-bin](https://github.com/romkatv/zsh-bin/releases) on aarch64 but the current version of the xxh-shell-zsh builds the x86_64 version.
Because xxh has no detecting the architecture (it know it but not using) you can solve this by these steps:
1. Fork the [xxh-shell-zsh](https://github.com/xxh/xxh-shell-zsh) repo and rename to `xxh-shell-zsh-aarch64`
2. Edit the [links section](https://github.com/xxh/xxh-shell-zsh/blob/91e1f84f8d6e0852c3235d4813f341230cac439f/build.sh#L27-L29): put the links to [zsh-bin version for aarch64 from release assets](https://github.com/romkatv/zsh-bin/releases)
3. Install your shell `xxh +I https://github.com/NoirJ0e/xxh-shell-zsh-aarch64` and connect `xxh host +s xxh-shell-zsh-aarch64`
4. Use it for the appropriate host or add it to [the config file](https://github.com/xxh/xxh/wiki#config-file)

**Comment by NoirJ0e** [comment]
Got it, problem solved
